package ollama

import (
	"bufio"
	"context"
	"errors"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"

	"advisor/internal/backend"
	"advisor/internal/hardware"
)

// ModelsFolder reports where Ollama keeps models, as Ollama itself says
// (ARCHITECTURE.md D-72, D-78), and who can change that. It reads and
// changes nothing.
//
// Ollama's API has no endpoint that returns the folder (D-71, fact 9), but
// it says so in two places, tried in this order:
//
//  1. the FROM line of /api/show's Modelfile for any installed local model:
//     "FROM <models folder>/blobs/sha256-<digest>";
//  2. the "server config" line the server logs when it starts, which lists
//     OLLAMA_MODELS as the server resolved it — the log this app captured
//     from an Ollama it started, or Ollama's own server.log where its app
//     runs the server, or the service's journal on Linux.
//
// When neither answers (Ollama has never run, or not been asked yet) the
// answer is Known == false with the OS default, labelled as where Ollama
// will put models: the same reading the hardware profile makes.
//
// It returns an error only when ctx ends: every source that cannot be read
// is simply the next one tried, because "the advisor could not tell" is an
// answer (Known == false), not a failure.
func (b *Backend) ModelsFolder(ctx context.Context) (backend.ModelsFolder, error) {
	out := backend.ModelsFolder{Control: b.folderControl()}
	if err := ctx.Err(); err != nil {
		return out, err
	}
	if dir, model, ok := b.folderFromInstalledModel(ctx); ok {
		out.Path, out.Known = dir, true
		out.How = "from a model Ollama has installed (" + model + ")"
		return out, nil
	}
	if err := ctx.Err(); err != nil {
		return out, err
	}
	if dir, ok := b.folderFromLog(ctx); ok {
		out.Path, out.Known = dir, true
		out.How = "from the log Ollama's server wrote when it started"
		return out, nil
	}
	if err := ctx.Err(); err != nil {
		return out, err
	}
	dir, source := b.defaultModelsFolder(ctx)
	if dir == "" || dir == hardware.Unknown {
		out.How = "Ollama has not said where it keeps models, and its default folder could not be worked out (" + source + ")"
		return out, nil
	}
	out.Path = dir
	out.How = "Ollama has not said where it keeps models yet, so this is where it will put them (" + source + ")"
	return out, nil
}

// defaultModelsFolder is the OS default, from the hardware package's own
// reading; tests replace it.
func (b *Backend) defaultModelsFolder(ctx context.Context) (dir, source string) {
	if b.defaultFolder != nil {
		return b.defaultFolder(ctx)
	}
	return hardware.DefaultModelsDir(ctx)
}

// maxShowTries bounds how many installed models are asked before giving up
// on Show: a model with no local blobs (Ollama's cloud models) has no FROM
// line to read, and the next one is tried, but not every model of a large
// library.
const maxShowTries = 5

// folderFromInstalledModel asks /api/show about installed models until one
// gives a FROM line with a blob path.
func (b *Backend) folderFromInstalledModel(ctx context.Context) (dir, model string, ok bool) {
	c := b.client(5 * time.Second)
	tags, err := c.tags(ctx)
	if err != nil {
		return "", "", false
	}
	tries := 0
	for _, m := range tags.Models {
		name := m.Model
		if name == "" {
			name = m.Name
		}
		if name == "" {
			continue
		}
		if tries++; tries > maxShowTries {
			break
		}
		s, err := c.show(ctx, name)
		if err != nil {
			continue
		}
		if dir, ok := folderFromModelfile(s.Modelfile); ok {
			return dir, name, true
		}
	}
	return "", "", false
}

var blobName = regexp.MustCompile(`^sha256-[0-9a-f]{64}$`)

// folderFromModelfile reads the models folder out of a Modelfile as
// /api/show returns it (v0.34.2, server/routes.go GetModelInfo):
//
//	# Modelfile generated by "ollama show"
//	# To build a new Modelfile based on this, replace FROM with:
//	# FROM llama3.2:1b
//
//	FROM /Users/me/.ollama/models/blobs/sha256-<64 hex digits>
//
// Only a FROM line that names a blob inside a "blobs" folder counts (the
// commented "# FROM llama3.2:1b" does not, nor a FROM naming another model),
// and the path is used in whatever separator it arrives in: the same reading
// serves Windows. A vision model has a second FROM line for its projector,
// in the same folder.
func folderFromModelfile(modelfile string) (string, bool) {
	for _, line := range strings.Split(modelfile, "\n") {
		line = strings.TrimRight(line, "\r")
		if !strings.HasPrefix(line, "FROM ") {
			continue
		}
		p := strings.TrimSpace(strings.TrimPrefix(line, "FROM "))
		if dir, ok := folderOfBlobPath(p); ok {
			return dir, true
		}
	}
	return "", false
}

// folderOfBlobPath is "<folder>/blobs/sha256-<digest>" → "<folder>".
func folderOfBlobPath(p string) (string, bool) {
	if !isAbsolutePath(p) {
		return "", false
	}
	i := strings.LastIndexAny(p, `/\`)
	if i < 0 || !blobName.MatchString(p[i+1:]) {
		return "", false
	}
	rest := p[:i] // "<folder>/blobs"
	j := strings.LastIndexAny(rest, `/\`)
	if j < 0 || rest[j+1:] != "blobs" {
		return "", false
	}
	dir := rest[:j]
	if dir == "" || strings.HasSuffix(dir, ":") { // "/blobs/…" and "C:\blobs\…" have no folder of their own
		return "", false
	}
	return dir, true
}

// isAbsolutePath accepts a path in either syntax: "/…", `C:\…` or `\\…`.
func isAbsolutePath(p string) bool {
	switch {
	case strings.HasPrefix(p, "/"), strings.HasPrefix(p, `\\`):
		return true
	case len(p) >= 3 && p[1] == ':' && (p[2] == '\\' || p[2] == '/'):
		c := p[0]
		return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
	}
	return false
}

// maxLogRead bounds how much of one log is scanned: the last stretch of it,
// since the newest "server config" line is what counts.
const maxLogRead = 64 << 20

// folderFromLog looks for the last "server config" line in the logs Ollama
// may have written to (this app's own capture first, D-46), then the
// service's journal on Linux.
func (b *Backend) folderFromLog(ctx context.Context) (string, bool) {
	for _, p := range b.modelsLogCandidates() {
		f, err := os.Open(p)
		if err != nil {
			continue
		}
		dir := lastServerConfigFolder(tailReader(f, maxLogRead))
		f.Close()
		if dir != "" {
			return dir, true
		}
	}
	if text := b.journalServerConfig(ctx); text != "" {
		if dir := lastServerConfigFolder(strings.NewReader(text)); dir != "" {
			return dir, true
		}
	}
	return "", false
}

// modelsLogCandidates are logCandidates plus the file this app captured on
// an earlier run (its supervised log stays in the data folder, and a
// server it started may have outlived this process).
func (b *Backend) modelsLogCandidates() []string {
	out := b.logCandidates()
	if dir, err := dataDir(); err == nil {
		mine := filepath.Join(dir, "ollama", "logs", "server-supervised.log")
		dup := false
		for _, p := range out {
			if p == mine {
				dup = true
			}
		}
		if !dup {
			out = append(out, mine)
		}
	}
	return out
}

// tailReader is f's last max bytes, starting at a line boundary.
func tailReader(f *os.File, max int64) io.Reader {
	fi, err := f.Stat()
	if err != nil || fi.Size() <= max {
		return f
	}
	if _, err := f.Seek(fi.Size()-max, io.SeekStart); err != nil {
		return f
	}
	br := bufio.NewReader(f)
	_, _ = br.ReadString('\n') // the partial first line
	return br
}

// journalServerConfig asks the system journal for the service's last
// "server config" lines, on Linux only (a systemd install logs there, not to
// a file). "" when there is no journalctl, no such unit, or it will not say.
func (b *Backend) journalServerConfig(ctx context.Context) string {
	if b.journal != nil {
		return b.journal(ctx)
	}
	if runtime.GOOS != "linux" {
		return ""
	}
	path, err := exec.LookPath("journalctl")
	if err != nil {
		return ""
	}
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	out, err := exec.CommandContext(ctx, path, "-u", "ollama", "--no-pager", "-o", "cat", "-g", "server config", "-n", "20").Output()
	if err != nil {
		return ""
	}
	return string(out)
}

// nextKey finds where a map value ends in Go's printed map[k:v k2:v2]: the
// next " KEY:". A value may itself hold spaces (a Windows folder like
// "C:\Users\Jo Smith\.ollama\models"), so the value cannot be cut at the
// first space; keys, unlike a path's words, are followed by a colon.
var nextKey = regexp.MustCompile(`\s[A-Za-z][A-Za-z0-9_]*:`)

// lastServerConfigFolder scans a log for the newest line Ollama's server
// writes at start-up (v0.34.2, server/routes.go Serve):
//
//	time=… level=INFO source=routes.go:… msg="server config" env="map[… OLLAMA_MODELS:/Users/me/.ollama/models …]"
//
// slog's text handler quotes and escapes the env value, so on Windows a
// backslash arrives doubled; strconv.Unquote undoes that. "" when no line
// names a folder.
func lastServerConfigFolder(r io.Reader) string {
	br := bufio.NewReader(r)
	last := ""
	for {
		line, err := br.ReadString('\n')
		if strings.Contains(line, "server config") && strings.Contains(line, "OLLAMA_MODELS:") {
			if dir := folderFromServerConfigLine(line); dir != "" {
				last = dir
			}
		}
		if err != nil {
			if !errors.Is(err, io.EOF) {
				return last
			}
			return last
		}
	}
}

func folderFromServerConfigLine(line string) string {
	line = strings.TrimRight(line, "\r\n")
	if !strings.Contains(line, `msg="server config"`) && !strings.Contains(line, "msg=server config") {
		return ""
	}
	_, after, ok := strings.Cut(line, " env=")
	if !ok {
		return ""
	}
	env := after
	if strings.HasPrefix(after, `"`) {
		q, err := strconv.QuotedPrefix(after)
		if err != nil {
			return ""
		}
		if env, err = strconv.Unquote(q); err != nil {
			return ""
		}
	}
	_, val, ok := strings.Cut(env, "OLLAMA_MODELS:")
	if !ok {
		return ""
	}
	if loc := nextKey.FindStringIndex(val); loc != nil {
		val = val[:loc[0]]
	} else {
		val = strings.TrimSuffix(strings.TrimSpace(val), "]")
	}
	val = strings.TrimSpace(val)
	if !isAbsolutePath(val) {
		return "" // an empty or relative value says nothing about where the models are
	}
	return val
}

// goos is runtime.GOOS; folderControl's tests set it to run every
// operating system's rules on any runner (the same seam as goarchForTest).
var goos = runtime.GOOS

// folderControl says who can change Ollama's models folder (D-72):
//
//   - macOS and Windows with Ollama's app installed: the app, whose Model
//     location setting the person changes (D-71, fact 1);
//   - Linux with Ollama's systemd unit installed: an administrator;
//   - an Ollama with no app and no service (a command-line install, or the
//     copy this app installs on Linux): the advisor, which starts it;
//   - nothing installed: unknown.
func (b *Backend) folderControl() backend.FolderControl {
	switch goos {
	case "darwin":
		if b.macAppInstalled() {
			return backend.FolderRuntimeApp
		}
	case "windows":
		if b.windowsAppInstalled() {
			return backend.FolderRuntimeApp
		}
	case "linux":
		if b.systemServiceInstalled() {
			return backend.FolderAdministrator
		}
	}
	if b.cliInstalled() {
		return backend.FolderAdvisor
	}
	return backend.FolderUnknown
}

func (b *Backend) isDir(p string) bool {
	_, isDir, ok := b.env.statSize(p)
	return ok && isDir
}

func (b *Backend) isFile(p string) bool {
	size, isDir, ok := b.env.statSize(p)
	return ok && !isDir && size > 0
}

func (b *Backend) macAppInstalled() bool {
	if b.isDir("/Applications/Ollama.app") {
		return true
	}
	if home, err := b.env.userHomeDir(); err == nil && home != "" {
		return b.isDir(strings.TrimRight(home, "/") + "/Applications/Ollama.app")
	}
	return false
}

// windowsAppInstalled looks for "ollama app.exe" (the tray app the
// installer puts beside ollama.exe): in the installer's default folder, and
// beside an ollama.exe found on the path.
func (b *Backend) windowsAppInstalled() bool {
	if lad := b.env.getenv("LOCALAPPDATA"); lad != "" {
		if b.isFile(strings.TrimRight(lad, `\/`) + `\Programs\Ollama\ollama app.exe`) {
			return true
		}
	}
	if p, err := b.env.lookPath("ollama.exe"); err == nil && p != "" {
		if i := strings.LastIndexAny(p, `\/`); i >= 0 && b.isFile(p[:i]+`\ollama app.exe`) {
			return true
		}
	}
	return false
}

// systemServiceInstalled: the unit Ollama's install script writes, or the
// one a distribution package ships.
func (b *Backend) systemServiceInstalled() bool {
	for _, p := range []string{
		"/etc/systemd/system/ollama.service",
		"/usr/lib/systemd/system/ollama.service",
		"/lib/systemd/system/ollama.service",
	} {
		if b.isFile(p) {
			return true
		}
	}
	return false
}

// cliInstalled: an ollama program on the path, or the copy this app
// installed under its data folder.
func (b *Backend) cliInstalled() bool {
	name := "ollama"
	if goos == "windows" {
		name = "ollama.exe"
	}
	if p, err := b.env.lookPath(name); err == nil && p != "" {
		return true
	}
	if dir, err := dataDir(); err == nil {
		return b.isFile(filepath.Join(dir, "ollama", "bin", "ollama"))
	}
	return false
}
